---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  # - ./flux-system-default-deny-all.yaml
  # - ./flux-system-allow-ig-from-prometheus.yaml
  - source-controller
  - kustomize-controller
  - flux-operator
  - helm-controller
  - notification-controller