apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  pushover_api_token: ENC[AES256_GCM,data:pAJLYmXICm6sWmoN9NB3c3yRvZJnKnOj+dNFGS7N,iv:mDMqzcvSr5Sl+omA9j8zjKT89utYavbY7Iwk5fC/NZw=,tag:JV8s/VFKEgssWpCSNzY9Gg==,type:str]
  pushover_api_userkey: ENC[AES256_GCM,data:JEhChUdxdGfcM70+FC0Y4LAtKphfjVZs4hYyH4FW,iv:yoQ8eHBh3Og0+acl0RxH6Wsm4ufKq7ZwIzV+Np9XRfY=,tag:h9hVZpZOIzfIfRxyZTZS6g==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WjVWZ0ZBWFFJQVlvb0hP
        aitmRHI0S08xY2pnVmRBT2lCeFkrcDAwbmpRCmZQLzAzczRIbTFZeHRXZ1BIbzg0
        OFN1QXNiSXdzZUMyNE5rcnJ3ZzVuZVEKLS0tIFl1SCtTVGZWakVqWUV1ZWVHMDlY
        cVNTY3R1cGhUaTYwT0g4eHU2TzFWNmcK5yVnvawZ1byAJBhXDDfmuantQFYzub9l
        8Q0w5uyGx6vtoFd7YVjjSYdcOs+3eNEHnRXlu+3W8lEBBWfgAS3LfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T22:09:57Z"
  mac: ENC[AES256_GCM,data:vJgLjdyaWvziOhOiWbk2a/zbIT91u/GiPRn2RN/nuMvTr6ck3cPIp4WmNUPxApBIHICYHI75AN4TjmIpjDYSMlrek0wON+xgXcGKDGDKic3OtKSv8k/plgNeBuEjXs5FZBtV20fqV+y/zHtHl9YcvJ01CzFprWWyrwUXmbAFNe0=,iv:N2diLgAeVpt95ttjZk0QhNVx4FdFDsJY88EwM20/SLA=,tag:ydVvzF7mBUP0msae3PoHiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
