---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ./flux-system-flux-operator-allow-eg-to-coredns.yaml
  - ./flux-system-flux-operator-allow-eg-to-k8s-api.yaml
  - ./flux-system-flux-operator-allow-eg-to-world.yaml
  #- ./flux-system-flux-operator-allow-ig-from-prometheus.yaml
  - ./flux-system-flux-operator-allow-ig-from-host.yaml