---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd-backup
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/kube-system/etcd-backup/app
  prune: true
  wait: true
  timeout: 2m
