---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade

resources:
  - ./system-upgrade-default-deny-all.yaml
  - ./system-upgrade-allow-eg-to-coredns.yaml
  - ./system-upgrade-allow-ig-from-prometheus.yaml
  - ./system-upgrade-tuppr-allow-eg-to-k8s-api.yaml
  - ./system-upgrade-tuppr-allow-eg-to-talos-api.yaml
  - ./system-upgrade-tuppr-allow-ig-from-k8s-api.yaml