---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: system-upgrade-tuppr-allow-eg-to-k8s-api
  namespace: system-upgrade
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tuppr
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: 6443
        protocol: TCP