---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: system-upgrade-tuppr-allow-eg-to-talos-api
  namespace: system-upgrade
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tuppr
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.50.0/24
      ports:
        - protocol: TCP
          port: 5000