---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: system-upgrade-tuppr-allow-eg-to-k8s-api
  namespace: system-upgrade
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tuppr
  policyTypes:
    - Egress
  egress:
    - toEntities:
      - kube-apiserver
      ports:
        - protocol: TCP
          port: 6443