---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ./cert-manager-cert-manager-allow-ig-from-prometheus.yaml
  - ./cert-manager-cert-manager-allow-eg-to-k8s-api.yaml
  - ./cert-manager-cert-manager-allow-ig-from-host.yaml
  - ./cert-manager-cert-manager-allow-eg-to-coredns.yaml
  - ./cert-manager-cert-manager-allow-ig-from-k8s-api.yaml