apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:emH5K/XWODwiFDQ6w5wEv8Ii5Jg1bnNaqIw+tpPJXkPdfkCsuTD5DA==,iv:kL1rrVDJjl+KTVCWWcLhpaTUQB9eFzP7BKzKg2qrQs8=,tag:lZ1ngeksU2PpZGHSzHrY9g==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYzNmTWVxL01BU3ZweFIv
        VzBTeW5NdGdleVFFMTRqZG54VExFamp4bjAwCjN3Q3NIQ3dJeDFIL1l5TGtaVHc2
        U2JEZTcyMzl1NlRFdFIyR1d4bFd0QVUKLS0tIGNCSGlDMDd1dzRidWVSemhRbUtn
        cjZRT2svTFRzc0dabFc3VWhSUnpYMXcKNlXeIej35rxeFi/9j6JoOeLnUoVWMUMB
        VPF8meTbe43Kh6SWNDo7g4yBonJxf5+CSZKzvodXeswTYHAETLcOfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T21:42:47Z"
  mac: ENC[AES256_GCM,data:rCkGdi1n7qeXZGlWHH5EC68gJuhFNtebKRbqVMOHgs4BUNdx2tSS6gv1NZTWB1p+ZTRv/MTRlk7OUK28emLJh85B2pbaRz1BMM4DdAM52qwTvLofd25es3nkzBVvhhMI99cX6yHQSQaLn87xMrU0IQwXQ3QqjjBrIp2Mvr2laEE=,iv:Pf9znpsXtvSNW6Q8R5abX951g1YBTTRd761KNjmtyxU=,tag:d5cA3y+rb1yG/MhKKn7PLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
