apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mQmxcRv6YpIj,iv:dPNNFKU/CFRO+3/EPsthxgNf748C0Kfq294kfep4jc8=,tag:Pke+1vhqiowOBiBVpBuzHg==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y2xsSUVKRlhnQ3lNR25r
        M3hYZUdteFVnSFdEK1RFaXFyV09FNm9wWlZvClN0MkhuV0JYQmc2TVNPYzdIZ2kv
        RnpSa1hqeWFjNU1VZmhEQUg3ZGJ5aDAKLS0tIEVTcmhrNnBtM21NMyt2MzFaZEFS
        K081RXoydmhUVnk4THdrd09tWnRNOVEKhezf8tV5Yq6w/4uYNRwcx8cUZ5y91Q0N
        oyOykwegg7OSxUbTJ5wmsa811OiQr/zPZm2Rz90T8gVuZW3a6ICZAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T21:42:47Z"
  mac: ENC[AES256_GCM,data:TV74FTvkxHRPtAxKhPptDm6cixKuFcnhPx8ebhWzrQHQC6g4LpXmJ3Hb3WOeZLipEMS9TNc6V3xw7uIEueudZy/3hlirUpRa7v433UoNZF+iuwJCimdZyq8vMjKNtzWcPaaFgqq8NDilwuU622z7MMleLy2ErPiccPmDgsHZnIk=,iv:onXzAFHT3nyR4yeBVTqCe9OOM2xiJGQLvlMW2Wb+Yjw=,tag:6FauCbQqwHvGrJORbkvU7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
