apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:F5z6WKehkG1oFcoUZoT772GPBR4ViVsBQBFTJi1BGmw=,iv:6J9ZpAEK5HdMVloCGT9OsY47QZifqABrhhhA/O0+8iA=,tag:KFAGxe5iDy0MVH91phPW9A==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcjJ5eUQwc1U0MVpYMmNH
        K3BTYWprQy9lZE0yL1VtZTQ5V3NDY2F2TFQ0Ckt2aHRMMm9CbGYxemU2VzY5ZDlY
        QWFkdkVRSHY1RnpOZmlpMGpYUGVEaDAKLS0tIFRkWU9MV2UvWWhyaE5wKzh5bWdW
        Yzk0TnZ5K25va0xkVXJIU0MzNGZia0kK35mr6JeKwDMZZK8oXtM12E3bGoRe5ysH
        R1I1kQgY9L3jhB6+Zq2yuPfAMPfJRt5guTTZ5lNXzvAKSqWEyYNOrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T21:42:47Z"
  mac: ENC[AES256_GCM,data:EuvMQ5spt8eWhvzbJZZFOt41PgkiIyNU7p2U6CIVpdetXRdcq+Lk6qsC2fkcHG8db2EvpHoKOgidhwcaPO/wqNmzEGD+xgYt38l+w1RhxzJxIB3+MP5g/yL7UFGvbsIPwVQs5/8oqrtn+OguKWEAP22Pq823PX81otQqsMdQP6M=,iv:BLL+Zw54Wfsx9s3h5DG8iz5uMpEKTAsXHQJK0DSCXZM=,tag:hLBlVe6y8CXNEMopDQGYww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
