apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:+9hPAqhRzEc2Bgf+33onrJQEYtUJ4P7qTyh5vZ14v6JC4uhVp1GjC2HdmigxT9wmqLiyjGhIxWvDJTNuMntTSQ==,iv:CPq+vCF5kn1gh8t9MBVJnUU5NbfbGgTZxQ/iMV3j3uY=,tag:ywVfhTNBnjkXbyZUkHpu2g==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM1JCWUQ3eUc2cVlrQWFu
        SkhOSlBlMFNUTUh6YzRlZlFZenpXNk82N1VjClRqZWFBOTNCTFM3b0M4L1dwMUk2
        SUJ0Z2xKdDhIL0JtYTlrclR4NFB1ZTAKLS0tIEppUy9TOTRGY25Rd1JTOEZBdmNs
        YVFuR0xvR3F6VVJTZm5WZFloZW9BdTAKNXt9edYTpcRl1PXbYNA+gMh148Nrvrlm
        eLaacB5sxa9+AvMP7lR7MF1s9/a4msQetZGvR+aHj/txi3VpVGjUkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T17:35:11Z"
  mac: ENC[AES256_GCM,data:VULhoq5OSYFz8pJw9FQNcCemgpXGjXo1OFWlFYYIdp1AM4oMu1ZJ5dY9sTevcT3OgChT2raWi5WQ1MSmgVlA7xhq5fA5Pf7a7fcn47P5EYhC/AeVnH0XtdA6FmyDY/dUTsHW2G/ypU/ojjtp4028XABah0oTjWaPsyKugf3B3Gg=,iv:wd66T5pAUTSHZa6ePxS9LlUSxuyGY7CFgNrVbqERDVM=,tag:IKVfsL1HNlBlciQeDSCH+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
