apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hQPM0Iori3+8rvycdIPkIoC5Kig=,iv:WNGlGuc8UhUcizJ1CUszI1Gs83TlJOE4I40ZK+OIM1I=,tag:WaiqabnRthjNrz/IRAixzA==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:b3h3ecOd2KN6Uq3If6di9kb35RPi/zGwolQ=,iv:CjZvLoOrEcOVYBh8erh8A9YTrvGJgyE1ZZ5v6q2ebMI=,tag:rS6FeVSJaxqJ4cgR72p30w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P6JvevE8kjbEFrRVxSBRqIxv/Vnxzl+uG2lJlvft08TtwOD47taP4w==,iv:xMMmW4obPzvv0/mM2W8NZ0tUK97HrSgQzxz6vPRgXI4=,tag:ZP/g0X0qRYXGpuPeHU98Og==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS0thWU1QVHdQb0l5R2Y4
        S0JTMmNhT1NWSjZLVTZXMHhkUHpDazBCN2pRCmJSdytBbExjYzBWK1dxcXZLQkhD
        VUdOM3p1N25jcThMaDd2S2hIc3pPSXMKLS0tIHNLUnVhck5aVmd6TUJua2pSWTFT
        YVV6SUx0SjZXVDdKaTZ4K1F4bkV1TGcKJFNq68U/s5JvVKWS2KnLfSd5CgMd8G35
        ual9wDnd+v3oxNYovNM+ii00QV0sqsM5zoLA2VxkPu89P+ZeLGBE7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T19:14:53Z"
  mac: ENC[AES256_GCM,data:MtNYHJ4+BYJVoinEX35g1wA9YdmMvcU/GPganCXK7weKy68T6OPAE9n8qVMIUGJMse96Yl28HzwcEU4MI453xlhKqmEK9xVox5hOXd1Krx8wYK80xbxDRhtHkpPxXlr535HlCygQmLzjj0hmENpNEPcCY4xU22eLiZt5Ej6SB6A=,iv:j5VZC+zlvg3O1ibVHnrphjxgzvfksx08grc3XhI+IeI=,tag:H1AoaFA7B9YaKb2EbYcAcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
