apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ULKu/oxlhaDjSeZohadlsnBKc9/hCuFrqhOLSF+FtUFBD1NYsn/brozq6kOCOHlWXAT/FjCVL8Xk3NNtqZERxnujhkDoyofFoMfLfcd2uYGavO6H5Gf3Q7cbOeOb5Fuvs+LIrI2CzwbReoIWdPC1owGr+rTvK9Dnf971HyJCE5FA+1o8WqtYCnZOp2A4OC6GPuJ+4mzrRlnNK7cIes9nLWx+NyTJm1JjFTnnJdRh44nFDxeu,iv:pnhNuYYQOVVv2Ecf/lFedGqkX1FuTXcks/H+jurwsXU=,tag:u8FWODxZd/Y24IxtbfS/dg==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVGdOaDdGT3F5eWZ5UFEw
        WFdydXl1ZTd6MGgwWnlGaENzS29HS1FFRFdRCndLMlRZZ3l0VE5qZzhYdXB2MW85
        bGNpSFV6a0tLS3hEMUhqZ013dm5vUkkKLS0tIHlWZ3dVY2ZyZXVSK1E1cEVOcm1v
        YXJBTHZsYlllQzRGeGRpTklLWng4enMKKqPi1MjFvMSb8z5wO5Ic3btBa6DLtUTe
        q4ST1rBjxrpKoR6plYpiImA3ihayJbLFWhQM6be0g4eOjl7L1NPqyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T21:42:47Z"
  mac: ENC[AES256_GCM,data:QJ5ubqpYwpmaSCjdbP1NLiHX/RzxQIPIJeJ5Ym6YhMq21ijuLRI+CQUT6JraLy4GMGzU8sYVlMuBTcLFD+Lhszr3qsN3w3Lnk5+IKshhiu3MpnIK1odduQCeqZBx1cv+kvJeJuj72AQAiMGn8bBoaVFYvO0sdn0/+pBP8zi+RVs=,iv:g44rCC45tWJ29EFXErFvwJM5z/qTm0cBcToYNPv0/fc=,tag:u4eSzrZIR01bQH06RzdnUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
