apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flux-system-notification-controller-allow-ig-from-kustomize-controller
  namespace: flux-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notification-controller
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
          podSelector:
            matchLabels:
              app.kubernetes.io/component: kustomize-controller
      ports:
        - protocol: TCP
          port: 9090