apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2AITUEMG3SEA+3jZQtldNxjlJhY04Q9iAUhBk1xuCf1W3gkexB+Ovw==,iv:iFAfA1D3+Y1UQBo3ZbrUqFN2t0KUXc2Cx5cJSk6Hi4I=,tag:+RVqKqyaub4wj54h5/uxCg==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUWRMdWsySVpwbEQ0eDFB
        ZmtPZklzeGNmaWs1RndVek8vbnBFQVgvaFc4Ck5qaHM0cnYxdzBiR3R0eHZqZzJV
        dFMxWEJ0d2FqNlZQZTRvUWlWcWdXK2cKLS0tIC9kZjh5R2FDdmJpYUhZRnBrditB
        OWJhNjc0N3IvOE5jUkMrZmgxUjJzOEkKpmcKUe1Y4cdXlCA0NukDlkJBG2xzy95s
        Q/UWtWNYwUJXKuorFMDL7clE7xjA8GpKY7zJRkn5dUQaQjx9BfJV6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T21:42:47Z"
  mac: ENC[AES256_GCM,data://rgQmlx1EqNjWJAV9XA37xBvkdpe/KL6778e/qvO/Foqm1YtZrEVsuKyoYPrFXMgOIIn7XwHjKPIwpphLg5HDFoM7BAuBtB4aZ5d6+8Ashq2LsE5aSAYiv/axtUZ1MtMe+VpElJZa7r+dxk0g4jzVx1OtdqitUnsDhS6Oty/9M=,iv:b1KzjgF43AoRtFRcGfiPt71t7AxpS17a7ojyoBzH7U0=,tag:Q7Arp+LgsTo4TwQ2HdXO2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
