apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: flux-system-source-controller-allow-ig-from-host
  namespace: flux-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: source-controller
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - protocol: TCP
              port: "9090"
            - protocol: TCP
              port: "9440"