apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flux-system-kustomize-controller-allow-eg-to-notification-controller
  namespace: flux-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: kustomize-controller
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
          podSelector:
            matchLabels:
              app.kubernetes.io/component: notification-controller
      ports:
        - protocol: TCP
          port: 9090