apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  pushover_api_token: ENC[AES256_GCM,data:axLMOECeQcAurY0=,iv:s9KJPsJwmWAJaUhwQd5/Q3KgFLJW6w/BTDso0gyCh7U=,tag:kZzngob612gd9R8zc6/8jA==,type:str]
  pushover_api_userkey: ENC[AES256_GCM,data:Mo1TVnF+fawMyQ==,iv:RLQdEH+QETRap85uTQt876FbtdOYksFXx3Um1gKcl1Y=,tag:a3LXx1V+L67p+ykGSJkmMg==,type:str]
sops:
  age:
    - recipient: age1gc7a4ma6xs7hnrq52ygv4ay6rlznmqr28s6mjptal2m0ghuf8ptqyqqq9p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WjVWZ0ZBWFFJQVlvb0hP
        aitmRHI0S08xY2pnVmRBT2lCeFkrcDAwbmpRCmZQLzAzczRIbTFZeHRXZ1BIbzg0
        OFN1QXNiSXdzZUMyNE5rcnJ3ZzVuZVEKLS0tIFl1SCtTVGZWakVqWUV1ZWVHMDlY
        cVNTY3R1cGhUaTYwT0g4eHU2TzFWNmcK5yVnvawZ1byAJBhXDDfmuantQFYzub9l
        8Q0w5uyGx6vtoFd7YVjjSYdcOs+3eNEHnRXlu+3W8lEBBWfgAS3LfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T19:29:35Z"
  mac: ENC[AES256_GCM,data:S//2WCIBWQBlQ+R+UQuutyzlt4+4twnkSL6LeyswbbGTcZ3YysW2MX9hpG6liQ2nnTM3w6ZsP8Wbpes70kLJixlOjT2BNwdnx92d1OgWsN0aPGKelmX32j2axcN+gHwL4srvxcMkUhT2XHgOGQG6SgWenQ/wcTqY1RaAi4/SW+8=,iv:Evh56arSEtDrzNtrB3wXjmClBfbgrMFXNk76euu6kwM=,tag:R67Ohl5ygSh/N5EbOief6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
