apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-webhook-allow-ig-from-envoy-gateway
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: webhook
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: network
      - podSelector:
          matchLabels:
            helm.toolkit.fluxcd.io/name: envoy-gateway
      ports:
      - protocol: TCP
        port: 443

